name: Minecraft_SPY_RUMBLE
version: '${project.version}'
main: net.cherryleaves.minecraft_spy_rumble.Minecraft_SPY_RUMBLE
api-version: '1.20'
author: sakuraba_jp
description: このゲームは【Spy Rumble】というゲームをモチーフにし、制作陣がこるんの名のもと勝手にMinecraft化したゲームのシステムプラグインである。
commands:
  task-spawn:
    aliases: [spawn, task-gold, gold]
    description: ここで入手した防具建てを金のスポーン場所に設置してください
  start:
    aliases: [start-book, werewolf-start]
    description: 人狼スタート本を入手するだけです。本当にゲームをスタートさせたい場合は本を開いてね